### ISSUE TITLE
minSdk is too low

### ISSUE THREAD

**Issue by ataulm** [Dorvaryn/unidirectionalDataFlow#1]
Some APIs unavailable on JB are being used (e.g. `setBackgroundColor(int, Theme)` - min Lollipop).

Either need to fix up these APIs or bump minSdk (totes would go for minSdk 21, given purpose of this project).

Looks like the Kotlin plugin and Lint doesn't play well, else it would have flagged it.

**Comment by Dorvaryn** [comment]
Fixed in master

**Comment by rock3r** [comment]
Lint support for Kotlin is coming in 1.0.2 (IDE only for now, CLI coming later on)
